apiVersion: v1
kind: Secret
metadata:
  name: {{ include "joget.fullname" . }}-db
  labels:
    {{- include "joget.labels" . | nindent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.secrets.dbPassword | b64enc | quote }}
 