---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
 name: joget
spec:
 selector:
   matchLabels:
     app: joget
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       app: joget
   spec:
     containers:
     - image: jogetworkflow/joget-enterprise
       name: joget
       resources:
          requests:
            cpu: "0.5"
            memory: "500Mi"
       env:
       - name: MYSQL_HOST
         value: "${MYSQL_SERVICE_HOST}"
       - name: MYSQL_PASSWORD
         valueFrom:
          secretKeyRef:
            name: {{ include "joget.fullname" . }}-db
            key: dbPassword
       - name: MYSQL_PORT
         value: "${MYSQL_SERVICE_PORT}"
       ports:
       - containerPort: 8080
         name: joget
       volumeMounts:
       - name: joget-persistent-storage
         mountPath: /opt/joget/wflow
     volumes:
     - name: joget-persistent-storage
       persistentVolumeClaim:
         claimName: joget-pv-claim
