apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-db
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  rootPassword: {{ .Values.secrets.rootPassword | b64enc | quote }}
 